### ISSUE TITLE
Add support for Bazaar

### ISSUE THREAD

**Issue by hardware** [mondediefr/docker-flarum#21]
The marketplace extension that allows you to add and remove extensions without composer or a terminal.

https://flagrow.io/
https://github.com/flagrow/bazaar/

Error after Bazaar installation :
```
2018/04/13 20:25:19 [error] 32#32: *28 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class Flagrow\Bazaar\Listeners\AddApiControllers does not exist in /flarum/app/vendor/illuminate/container/Container.php:741
Stack trace:
#0 /flarum/app/vendor/illuminate/container/Container.php(741): ReflectionClass->__construct('Flagrow\\Bazaar\\...')
#1 /flarum/app/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('Flagrow\\Bazaar\\...', Array)
#2 /flarum/app/vendor/flarum/core/src/Foundation/Application.php(514): Illuminate\Container\Container->make('Flagrow\\Bazaar\\...', Array)
#3 /flarum/app/vendor/illuminate/events/Dispatcher.php(149): Flarum\Foundation\Application->make('Flagrow\\Bazaar\\...')
#4 /flarum/app/vendor/illuminate/events/Dispatcher.php(135): Illuminate\Events\Dispatcher->resolveSubscriber('Flagrow\\Bazaar\\...')
#5 /flarum/app/vendor/flagrow/bazaar/bootstrap.php(9): Illuminate\Events\Dispatcher->subscribe('Flagrow\\Bazaar\\...')
#6 [internal function]: Flarum\Extension\ExtensionServiceProv" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "127.0.0.1:8888"
```

Issue opened here : https://github.com/flagrow/bazaar/issues/110

**Comment by pojntfx** [comment]
Using the following command, I was able to install bazar and then install extensions with it from the admin panel (it showed errors while installing them, but they worked flawlessly anyways) from inside the container:

 `sh -c "cd /flarum/app; composer require flagrow/bazaar;"`

My docker-compose:

```docker
version: "3"

services:
  web:
    image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
    ports:
      - "8888:8888"
    environment:
      - FORUM_URL=http://192.168.178.44
      - DB_PASS=YOUR_PASSWORD_HERE
      - DEBUG=true
    networks:
      - opensdcp-forum
    volumes:
      - opensdcp-forum-web-assets-data:/flarum/app/assets
      - opensdcp-forum-web-extensions-data:/flarum/app/extensions
    depends_on:
      - db

  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD_HERE
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=YOUR_USERNAME_HERE
      - MYSQL_PASSWORD=YOUR_PASSWORD_HERE
    networks:
      - opensdcp-forum
    volumes:
      - opensdcp-forum-db-data:/var/lib/mysql

networks: 
  opensdcp-forum:

volumes: 
  opensdcp-forum-web-assets-data:
  opensdcp-forum-web-extensions-data:
  opensdcp-forum-db-data:
```

**Comment by hardware** [comment]
It does not work for me, even with your method. You don't have any of this errors : https://github.com/flagrow/bazaar/issues/110 ? 

Another docker mystery I suppose...
